version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  # Laissez vide si vous n'avez pas de mot de passe
      - MYSQL_DATABASE=kaddem_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-kaddem:
    depends_on:
      - mysqlDb
    image: ihebkh336/kaddem-app  # Utilisez le nom de l'image Docker que vous avez construite
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
