version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-kaddem:
    depends_on:
      - mysqlDb
    image: zaymen/kaddem:0.0.1
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: